### ISSUE TITLE
jackson configOverride method not found since upgrading to 0.2.0

### ISSUE THREAD

**Issue by cpassar** [drallgood/jpasskit#400]
I was using version 0.1.1 and it was working great except for the timestamp format.  I upgraded to 0.2.0 and made the necessary changes to move to the builder classes.  I compile successfully and I have tried excluding standard wildfly jackson libraries but I cannot seem to get past this error.  Am I the only one seeing this?  I tried reverting back to a prior version and the issue seems to appear in 0.1.2 and later.

Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectMapper.configOverride(Ljava/lang/Class;)Lcom/fasterxml/jackson/databind/cfg/MutableConfigOverride;
	at de.brendamour.jpasskit.signing.PKAbstractSigningUtil.configureObjectMapper(PKAbstractSigningUtil.java:131)
	at de.brendamour.jpasskit.signing.PKAbstractSigningUtil.<init>(PKAbstractSigningUtil.java:66)
	at de.brendamour.jpasskit.signing.PKFileBasedSigningUtil.<init>(PKFileBasedSigningUtil.java:50)
	at com.kwi.ws.wallet.service.PassKitGenerator.createPasskit(PassKitGenerator.java:240)
	at com.kwi.ws.wallet.resource.WalletResource.iosSignCoupon(WalletResource.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:395)
	... 32 more

**Comment by drallgood** [comment]
it probably means you have some sort of dependency conflict. 
jPasskit is always using the latest dependencies nowadays and if you have older dependencies in your list, it may cause issues sometimes. Usually manifesting in Method/ClassNotFound exceptions

Unfortunately, that's something you have to resolve on your side.

**Comment by drallgood** [comment]
what might help figuring out where the dependency is coming from is the maven dependency tree plugin.
try `mvn dependency:tree` then look for older jackson versions
